### ISSUE TITLE
checkpoint link is expired

### ISSUE THREAD

**Issue by knwoo** [rohjunha/language-grounded-driving#2]
The command for 

`wget -N http://54.201.45.51:5000/exp40/exp40.tar.gz`

does not work. Is there any other link to get the checkpoint?

+ What's the role of json files in `.carla/dataset/evaluation/town1`  ? I can't get the meaning of data inside of it.

**Comment by rohjunha** [comment]
Hi @kaiiwoo, I think the link is valid from my side. You may download it from another IP address. I uploaded it to `./.carla/checkpoints/` as well.
Those files in the directory contain raw data for evaluation and low-level and high-level segmentation of the data.

**Comment by kaiiwoo** [comment]
Thanks for the update. Specifically, I'm curious about more specific information of the JSON file. 

When I `.split(',')` the element of each nested list of value of ['drives'], I found the lengths are identical as 21. 

This is my data parse code

```
import json
import pandas as pd

name = 'firstleft'
file = pd.read_json(f'{name}.json')
print(file['drives'].iloc[0][0].split(','))
print(len(file['drives'].iloc[0][0].split(',')))```

and the output was

```
['195.2322998046875', '55.487239837646484', '-0.010108298622071743', '0.034874942153692245', '179.99383544921875', '-0.06338498741388321', '-4.683960914611816', '0.0005152522935532033', '2.8605461466213455e-07', '-0.00023297438747249544', '4.169376552454196e-06', '0.00020997914543841034', '0.0', '-0.00028728158213198185', '4.004764832643559e-06;0.47066110372543335', '-4.355000328359893e-06', '0.0', 'False', 'False', '0', 'False;3869789844470666235;LANEFOLLOW;LANEFOLLOW']
21
```

What does each element in the list mean? and can I also generate the data using  `data_generator.py`?

**Comment by knwoo** [comment]
> Hi @kaiiwoo, I think the link is valid from my side. You may download it from another IP address. I uploaded it to `./.carla/checkpoints/` as well. Those files in the directory contain raw data for evaluation and low-level and high-level segmentation of the data.

Thanks for the update. Specifically, I'm curious about more specific information of the JSON file. 

When I `.split(',')` the element of each nested list of value of ['drives'], I found the lengths are identical as 21. 

This is my data parse code

```
import json
import pandas as pd

name = 'firstleft'
file = pd.read_json(f'{name}.json')
print(file['drives'].iloc[0][0].split(','))
print(len(file['drives'].iloc[0][0].split(',')))
```
and the output was

```
['195.2322998046875', '55.487239837646484', '-0.010108298622071743', '0.034874942153692245', '179.99383544921875', '-0.06338498741388321', '-4.683960914611816', '0.0005152522935532033', '2.8605461466213455e-07', '-0.00023297438747249544', '4.169376552454196e-06', '0.00020997914543841034', '0.0', '-0.00028728158213198185', '4.004764832643559e-06;0.47066110372543335', '-4.355000328359893e-06', '0.0', 'False', 'False', '0', 'False;3869789844470666235;LANEFOLLOW;LANEFOLLOW']
21
```

What does each element in the list mean? and can I also generate the same kind of data using  `data_generator.py`?
