### ISSUE TITLE
Specific data information 

### ISSUE THREAD

**Issue by knwoo** [rohjunha/language-grounded-driving#3]
Hi, thank you for the recent update. Specifically, I'm curious about information of the  `.carla/dataset/evaluation/townx/[direction].json`. I have 3 simple questions.

Q1. When I `.split(',')` the element of each nested list of value of ['drives'], I found the lengths are identical as 21. 

This is my data parse code

```
import json
import pandas as pd

name = 'firstleft'
file = pd.read_json(f'{name}.json')
print(file['drives'].iloc[0][0].split(','))
print(len(file['drives'].iloc[0][0].split(',')))
```
and the output was

```
['195.2322998046875', '55.487239837646484', '-0.010108298622071743', '0.034874942153692245', '179.99383544921875', '-0.06338498741388321', '-4.683960914611816', '0.0005152522935532033', '2.8605461466213455e-07', '-0.00023297438747249544', '4.169376552454196e-06', '0.00020997914543841034', '0.0', '-0.00028728158213198185', '4.004764832643559e-06;0.47066110372543335', '-4.355000328359893e-06', '0.0', 'False', 'False', '0', 'False;3869789844470666235;LANEFOLLOW;LANEFOLLOW']
21
```

What does each element in the list mean? and can I also generate the same kind of data using  `data_generator.py`?

Q2. What's the differenece direction w/ redundant or ordinal expression? (e.g., `straight, straingt.json` vs. `straight.json` & `firstleft.json` vs. `left.json`) I guess redundant expression is used to determine action when agent meets intersection

Q3. I want to figure out what each file mean in `carla/dataset/info/semanticN-v37/`

**Comment by rohjunha** [comment]
Hi @kaiiwoo, I think we have discussed this in the email thread. You can check how the data is parsed from https://github.com/rohjunha/language-grounded-driving/blob/master/data/types.py#L150. This is a concatenation of the state of the car, a control of the car, a waypoint id, and road options that are related to the labels of the waypoint.
Yes, `OfflineGeneratorEnvironment` should generate data.

I believe the redundant expression indicates cases where their actions are repeated twice. The ordinal expression means expressions that contain numbers such as first turn or second turn.

`data.mdb` contains raw driving data. `segment.json` has information to transform raw data into low-level and high-level segments. Low-level segments contain unit actions and are defined by multiple DriveData. High-level segments define sentence-level behavior including multiple low-level segments. For instance, high-level turning behavior includes going straight to the intersection, turning at the intersection, and (optionally) stopping after the turn. In this example, a single high-level segment 'left' will have three low-level segments with the labels of 'lanefollow', 'left', and 'stop'. `second_turn.json` contains indices of high-level segments to properly assign ordinal sentences when they are used in the evaluation.
